version: "3"
services:
  mysql:
    image: "mysql:5.7.21"
    volumes:
      - "./mysql:/var/lib/mysql"
    container_name: qrcode-scrap-mysql
    command: ["mysqld", "--character-set-server=utf8mb4", "--collation-server=utf8mb4_unicode_ci"]
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: mysql
  redis:
    image: "redis:4.0.6"
    container_name: qrcode-scrap-redis
    ports:
      - "6379:6379"
